user:
  id: 1
  name: Didnelpsun
  birthday: 2022/3/10
  sex: true
  primeAccount:
    id: 1
    name: 黄金账户 \n 测试
    userid: 1
    money: 10040.54
  interests:
    - 动漫
    - 小说
  accounts:
    - id: 1
      name: 黄金账户
      userid: 1
      money: 10040.54
    - id: 2
      name: 白银账户
      userid: 1
      money: 225.95
    - id: 3
      name: 钻石账户
      userid: 1
      money: 7466.72
  scores:
    Englist: 78.5
    Politics: 80.0
    Math: 135.0
    Computer: 140.5

spring:
  datasource:
    druid:
      # 开启监控和防火墙
      filters: stat,wall
      aop-patterns:
        - org.didnelpsun.boot.*
      # 开启监控页
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: root
        # 必须开启这个运行才能使用
        allow: ""
      # 开启web监控过滤器
      web-stat-filter:
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*ico,/druid/*'

    url: jdbc:mysql://localhost:3306/data
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    driver_class_name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      # 设置单个文件大小
      max-file-size:
        5MB
      # 设置单次请求文件的总大小
      max-request-size:
        50MB

mybatis:
#  config-location: classpath:mybatis.xml
  # 如果DAO的SQL映射XML文件与DAO接口Java文件同目录可以不写这个配置
  mapper-locations:
    - classpath:dao/*.xml
  # 配置了configuration就不能配置config-location来指定配置文件，否则会冲突
  configuration:
    map-underscore-to-camel-case: true
